#!/bin/bash
# Script para configurar las IPs iniciales de las VMs
# Debe ejecutarse DIRECTAMENTE en cada VM via consola ESXi

echo "=== Configuración inicial de red para vm_jhonatan ==="
echo "Ejecuta estos comandos EN LA CONSOLA DE vm_jhonatan:"
echo ""
echo "# 1. Verificar interfaces disponibles"
echo "ip link show"
echo ""
echo "# 2. Configurar interfaz LAN con IP estática (ajusta el nombre de la interfaz)"
echo "sudo nmcli connection add type ethernet ifname ens192 con-name lab-lan \\"
echo "  ipv4.method manual ipv4.addresses 192.168.50.1/24 connection.autoconnect yes"
echo ""
echo "# 3. Configurar interfaz WAN con DHCP"
echo "sudo nmcli connection add type ethernet ifname ens33 con-name wan-dhcp \\"
echo "  ipv4.method auto connection.autoconnect yes"
echo ""
echo "# 4. Activar conexiones"
echo "sudo nmcli connection up lab-lan"
echo "sudo nmcli connection up wan-dhcp"
echo ""
echo "# 5. Verificar configuración"
echo "ip addr show"
echo "ip route show"
echo ""
echo "# 6. Asegurar SSH está activo"
echo "sudo systemctl enable --now ssh"
echo "sudo systemctl enable --now sshd"
echo ""
echo "============================================="
echo ""
echo "=== Configuración inicial de red para mint_jhonatan ==="
echo "Ejecuta estos comandos EN LA CONSOLA DE mint_jhonatan:"
echo ""
echo "# 1. Verificar interfaces disponibles"
echo "ip link show"
echo ""
echo "# 2. Configurar interfaz para recibir IP por DHCP"
echo "sudo nmcli connection add type ethernet ifname ens192 con-name lan-dhcp \\"
echo "  ipv4.method auto connection.autoconnect yes"
echo ""
echo "# 3. Activar conexión"
echo "sudo nmcli connection up lan-dhcp"
echo ""
echo "# 4. Verificar que recibe IP (debería ser 192.168.50.x)"
echo "ip addr show"
echo ""
echo "# 5. Asegurar SSH está activo"
echo "sudo systemctl enable --now ssh"
echo "sudo systemctl enable --now sshd"
echo ""
echo "============================================="
echo ""
echo "DESPUÉS de ejecutar estos comandos en ambas VMs, podrás usar Ansible desde la VM de control"